name: Test Json

on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    inputs:
      services:
        description: 'Services to build and deploy (comma separated): "api-gateway","api-service","etc service"'
        default: '"api-gateway","api-service"'
        required: true

jobs:
  TestJson:
    runs-on: ubuntu-latest
    #Matrix Strategy
    strategy:
      fail-fast: true
      matrix:
        include:
          - text: ${{ fromJSON(format('[{0}]', inputs.services)) }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Run a multi-line script
        run: |
          echo ${{ matrix.text }}
